### ISSUE TITLE
error: recursive dependency detected!

### ISSUE THREAD

**Issue by hejiawencc** [openwrt/routing#1000]
Description:

```
Collecting package info: done
tmp/.config-package.in:92125:error: recursive dependency detected!
tmp/.config-package.in:92125:   symbol PACKAGE_nodogsplash depends on PACKAGE_opennds
tmp/.config-package.in:92144:   symbol PACKAGE_opennds depends on PACKAGE_nodogsplash
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"
```

**Comment by mwarning** [comment]
hi @hejiawencc, how can we reproduce this issue? I tried, but wasn't able to.
I build some image with nodogsplash and opennds both selected as module and it worked.
Building an image with nodogsplash only included worked as well.

**Comment by mwarning** [comment]
@bluewavenet fyi

**Comment by bluewavenet** [comment]
@hejiawencc 
Just giving us an error message from somewhere without any context is not very helpful.
Can you describe what it was you were doing when you saw the error?

**Comment by mwarning** [comment]
* https://github.com/openwrt/routing/pull/1002
* https://github.com/openwrt/routing/pull/1001

**Comment by hejiawencc** [comment]
Good morning. I'm very sorry that I didn't provide enough useful information, if there is a next time, I will make improvements.

Glad this issue has been resolved by #1002

**Comment by mwarning** [comment]
fixed

**Comment by mwarning** [comment]
@hejiawencc thank you for reporting this issue. We failed to notice it. :-)
