### ISSUE TITLE
Remove or keep bird-openwrt packets?

### ISSUE THREAD

**Issue by p4u** [openwrt/routing#277]
The bird integration to UCI/LUCI was made by Eloi, a student which is now out of the map. I pushed the packets to the oprnwrt-routing repository with the idea that he would maintain them, however I don't think it is gonna happen. Is there anyone interested on taking care of the maintenance? If not, I would remove them at least from the official repository.  

https://github.com/openwrt-routing/packages/tree/master/bird-openwrt

**Comment by eloicaso** [comment]
Dear Pau,

As you say, I have not been actively maintaining the package (lack of time). However, I just have started updating it as I could make it part of my MSc. project.

**Comment by tohojo** [comment]
Any plans to support Bird 2.0?

**Comment by eloicaso** [comment]
Yes, I already started looking at it and how Bird2 manages configuration now. However, I have had no spare time yet to properly start developing it. Moreover, I am still unsure about how bird1/2 separation will be handled (https://github.com/openwrt-routing/packages/pull/340)

**Comment by tohojo** [comment]
Eloi <notifications@github.com> writes:

> Yes, I already started looking at it and how Bird2 manages
> configuration now. However, I have had no spare time yet to properly
> start developing it. Moreover, I am still unsure about how bird1/2
> separation will be handled
> (https://github.com/openwrt-routing/packages/pull/340)

Ah, awesome, didn't see that pull request. Not sure there's a reason to
keep bird 1.6 around if you can support the 2.0 config format in uci.
The upgrade cost is mostly in configuration file format changes...

**Comment by briantopping** [comment]
Please don't delete this package. Even if it is out of date, it is better than nothing.

**Comment by rogerpueyo** [comment]
Hi @p4u,

I'm maintaining the bird1-openwrt packages now, so you may want to close this issue.

Cheers!
