### ISSUE TITLE
miniupnpd is flooding syslog with trace

### ISSUE THREAD

**Issue by Menion2k** [openwrt/routing#278]
Hi
On both openwrt/Lede miniupnpd is flooding the logs with:

`Sat Feb 25 13:09:28 2017 daemon.warn miniupnpd[2565]: SSDP packet sender [fd93:d5a1:21f1::1]:37057 not from a LAN, ignoring
Sat Feb 25 13:09:28 2017 daemon.warn miniupnpd[2565]: SSDP packet sender [fd93:d5a1:21f1::1]:37057 not from a LAN, ignoring
Sat Feb 25 13:09:28 2017 daemon.warn miniupnpd[2565]: SSDP packet sender [fd93:d5a1:21f1::1]:37057 not from a LAN, ignoring
`

**Comment by ecsv** [comment]
This package was removed in 20987707105119f50487711682bb269762ef43c9. So this ticket should most likely be closed
