### ISSUE TITLE
luci-app-bmx6: show the number of nodes in the network

### ISSUE THREAD

**Issue by rogerpueyo** [openwrt/routing#551]
(From https://dev.qmp.cat/issues/339)

When more than a few nodes are in the mesh, it becomes difficult to count them. Adding a counter to the Status or the Nodes page would be helpful.

@pedrolab, @axn

**Comment by rogerpueyo** [comment]
By the way, luci-app-bmx6 is in the openwrt-routing packages repository, while luci-app-bmx7 is in the luci repository (https://github.com/openwrt/luci/tree/master/applications/luci-app-bmx7).

Which one is the best?

**Comment by FreifunkUFO** [comment]
at least on luci-app-bmx7 there is "number of nodes" shown on the bmx7 status-page
![Bildschirmfoto_2020-10-28_14-37-35](https://user-images.githubusercontent.com/2579265/97445811-f20b9480-192d-11eb-87a3-a953d1e0d0af.png)
p.s. bmx6 and bmx7 are not compatible to each other (to run it on one network)

**Comment by BKPepe** [comment]
BMX6 was removed in https://github.com/openwrt/routing/commit/9fb9d9343ea27d6dbb5008ece10c0c843dd2c781, thus closing.
