### ISSUE TITLE
luci-app-bmx6: Links, Chat, Graph and Config views are not working in snapshot

### ISSUE THREAD

**Issue by pedro-nonfree** [openwrt/routing#569]
version: `OpenWrt SNAPSHOT r13150-47f17b0662 / LuCI Master git-20.126.80862-2a94e18`

These views fail this way [1]:

- <host>/cgi-bin/luci/admin/network/BMX6/Links
- <host>/cgi-bin/luci/admin/network/BMX6/Graph (fails silently, seen in syslog)
- <host>/cgi-bin/luci/admin/network/BMX6/Chat
- <host>/cgi-bin/luci/admin/network/BMX6/Configuration

which means that URL here is nil https://github.com/openwrt-routing/packages/blob/master/luci-app-bmx6/bmx6/usr/lib/lua/luci/model/bmx6json.lua#L49 

then https://github.com/openwrt-routing/packages/blob/master/luci-app-bmx6/bmx6/usr/lib/lua/luci/model/bmx6json.lua#L52 is incorrect and it should be (as pointed by @jow- in IRC) `if not url then`

but this works correctly in shell

```
# lua -lluci.model.uci -e 'print(luci.model.uci.cursor():get("luci-bmx6","luci","json"))'
exec:/www/cgi-bin/bmx6-info -s
```

[1]

```
/usr/lib/lua/luci/util.lua:140: attempt to get length of local 't' (a boolean value)
stack traceback:
	/usr/lib/lua/luci/util.lua:140: in function 'split'
	/usr/lib/lua/luci/model/bmx6json.lua:57: in function 'get'
	/usr/lib/lua/luci/controller/bmx6.lua:145: in function </usr/lib/lua/luci/controller/bmx6.lua:144>
```

**Comment by FreifunkUFO** [comment]
have a look at https://github.com/bmx-routing/bmx7/issues/56
and your browser-extensions-network-analysis. 
is it the "$ to %24" convertion problem?
p.s. i saw, luci-app-bmx7 is less complex than luci-app-bmx6, but almost the same code..

**Comment by BKPepe** [comment]
- BMX6 was removed in https://github.com/openwrt/routing/commit/9fb9d9343ea27d6dbb5008ece10c0c843dd2c781
- LuCI-app-BMX6 was removed in https://github.com/openwrt/routing/commit/c2124dd2ad542f526ee84e1984f03dd2f5b34dfe

Thus closing.
