### ISSUE TITLE
hnetd dependency on iptables

### ISSUE THREAD

**Issue by champtar** [openwrt/routing#652]
Hi @sbyx 

hnetd is using iptables directly here: https://github.com/sbyx/hnetd/blob/master/generic/tunnel.script#L11

firewall4 is based on nftables and thus hnetd might work if using iptables-nft but will break if using iptables-legacy
please consider adding a dependency on iptables, and if possible use procd firewall objects (exemples https://github.com/search?p=2&q=org%3Aopenwrt+json_add_array+firewall&type=Code)

**Comment by mwarning** [comment]
I assume that this is resolved now, since the linked MR was merged.
