### ISSUE TITLE
Move to openwrt/routing.git

### ISSUE THREAD

**Issue by aparcar** [openwrt/routing#663]
Hi, I'd like to finally move this repository to openwrt/routing.git rather than keeping it under a different organization name.

For starters, having it under a different name messes up access rights, e.g. when developers want to branch for a new release.

Please grant me full access on this repository and I'll do the move. GitHub automatically handles forwarding of Git setups which still use the "old" address.

**Comment by mwarning** [comment]
I remember there was a discussion about this. Can we link it here?

**Comment by aparcar** [comment]
It was initially [here](https://github.com/openwrt-routing/packages/issues/184) which suggested to merge it into packages.git, something I'd still prefer but clearly accept the maintainers concerns (see thread). Since the move doesn't "fix" the linked issue I decided to open a new one.

**Comment by mwarning** [comment]
I would be willing to give this a go. But I like to get a yes or no from the members of openwrt-routing:
@wfleurant, @oryon, @altergui, @simonwunderlich,  @sbyx, @jow-, @elektra42, @axn, @fingon, @ffainelli, @p4u, @acinonyx, @zioproto, @zorun, @kerneis, @mwarning, @lynxis, @lperkov, @bittorf, @lindnermarek, @nolith

If we get a majority, I will let @aparcar take care of the rest.

**Comment by PolynomialDivision** [comment]
@mwarning you did both? xD

**Comment by mwarning** [comment]
@PolynomialDivision it was meant as a visual hint (removed now) :-)

**Comment by lindnermarek** [comment]
Moving the repository to openwrt/routing.git while preserving the current structure & permissions works for me.

Gave my thumbs up.

**Comment by elektra42** [comment]
Fine for me, too.Regards,ElektraAm 04.06.2021 12:32 schrieb lindnermarek ***@***.***>:
Moving the repository to openwrt/routing.git while preserving the current structure & permissions works for me.
Gave my thumbs up.

**Comment by PolynomialDivision** [comment]
> It was initially [here](https://github.com/openwrt-routing/packages/issues/184) which suggested to merge it into packages.git, something I'd still prefer but clearly accept the maintainers concerns (see thread). Since the move doesn't "fix" the linked issue I decided to open a new one.

I would also prefer merging it into packages feed. Just for the reason that this community has a lot of active reviewers. If you do a PR there, you instantly get feedback. It is always nice to have some other people watching on what you do even if you are maintainer.

**Comment by lindnermarek** [comment]
> I would also prefer merging it into packages feed. Just for the reason that this community has a lot of active reviewers. If you do a PR there, you instantly get feedback. It is always nice to have some other people watching on what you do even if you are maintainer.

Please read the original conversation on this topic: https://github.com/openwrt-routing/packages/issues/184

**Comment by aparcar** [comment]
It's been a week, would you kindly make me a repository owner?

**Comment by aparcar** [comment]
I will no proceed moving this repository, first it will be renamed to `routing` and then moved to `openwrt/routing`.

**Comment by wfleurant** [comment]
boh!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by aparcar** [comment]
I finished the move, all current maintainers are invited as admins to the new repository.

**Comment by wfleurant** [comment]
wicked glad to see this is happen'in! cheers all,

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mwarning** [comment]
Thanks @aparcar for doing this.

**Comment by simonwunderlich** [comment]
@aparcar I don't have access to the new repo, can you please check? I would like to merge the batman-adv merge requests. thank you!

**Comment by aparcar** [comment]
I've added you.
