### ISSUE TITLE
Pin routing-repo on openwrt organisation

### ISSUE THREAD

**Issue by SvenRoederer** [openwrt/routing#689]
After moving the routing-feed to OpenWrt orga, it should be pinned like packages and luci-feeds.

**Comment by mwarning** [comment]
What is pinning?

**Comment by SvenRoederer** [comment]
https://github.com/openwrt

![Pin repos](https://user-images.githubusercontent.com/1755362/121944935-83ac0300-cd53-11eb-95f4-50ba3df37bc1.png)

**Comment by mwarning** [comment]
Ah, I see.

**Comment by PolynomialDivision** [comment]
That needs openwrt admin permission. So maybe @aparcar can do that.

**Comment by aparcar** [comment]
Done
