### ISSUE TITLE
miniupnpd: ieee80211 phy0: rt2x00queue_write_tx_frame: Error - Dropping frame due to full tx queue 2

### ISSUE THREAD

**Issue by braveheartleo** [openwrt/routing#72]
Using miniupnpd-1.9.20141128-1, I'm getting multiple errors in the kernel logs as follows

```
 ieee80211 phy0: rt2x00queue_write_tx_frame: Error - Dropping frame due to full tx queue 2
```

Because of this, my wireless clients remain connected but could not access the network nor the internet. This has been observed on an Asus RT-N13U B1 running CHAOS CALMER (Bleeding Edge, r43749).

In case it matters, I have setup two VAPs, each with a different subnet, on a single physical wireless interface.

Reverting back to Barrier Breaker's miniupnpd-1.8.20140523-4 does not exhibit this issue.

**Comment by ecsv** [comment]
This package was removed in 20987707105119f50487711682bb269762ef43c9. So this ticket should most likely be closed
