### ISSUE TITLE
Hacktober

### ISSUE THREAD

**Issue by PolynomialDivision** [openwrt/routing#728]
Can we participate in [hacktober](https://hacktoberfest.digitalocean.com/)? If you review 4 PRs or do 4 PRs against this repository, you get a free t-shirt. We would nee to add the `hacktober` label to this repository.

Openwrt/packages is alreay part of it.

**Comment by PolynomialDivision** [comment]
What do you thing people of @openwrt/routing-admin ?

**Comment by mwarning** [comment]
Let's try it. :-)
In the worst case we get a lot of "fake" PRs.

**Comment by PolynomialDivision** [comment]
okay, I added it :)

**Comment by aparcar** [comment]
Please keep an eye on the [spam](https://drewdevault.com/2020/10/01/Spamtoberfest.html) :)

**Comment by PolynomialDivision** [comment]
Hacktober is finished. I will close.
