### ISSUE TITLE
Certain upstream switch to `firewall4` aka `nftables` instead of `iptables`

### ISSUE THREAD

**Issue by aparcar** [openwrt/routing#731]
Hi all, especially @openwrt/routing-write,

for the next OpenWrt release `firewall4` is [considered](https://github.com/openwrt/openwrt/pull/4642) as a replacement of the current `iptables` based `firewall` package. While the configuration stays within `/etc/config/firewall`, packages using `iptables` directly may see trouble.

This is a heads up for everyone maintaining such packages but also please post packages here that would be affected so a smother migration is possible.

Compatible with `firewall4`:
- [x] OLSR

Heads up for packages.git: https://github.com/openwrt/packages/issues/16818
Heads up for luci.git: https://github.com/openwrt/luci/issues/5409

**Comment by PolynomialDivision** [comment]
OLSR is affected.

**Comment by pmelange** [comment]
> OLSR is affected.

with a ```git grep -i iptables``` i see that nodogsplash and opennds both require "iptables-mod-ipopt".  What would be the equivalent package in fw4?

In OLSR, it seems like only olsrd/files/olsrd.sh is using iptables and ip6tables in a script.  Is there a syntax change on the command line going from iptables to fw4?

I didn't look at any of the source code of any of the packages, just at the repo itself.

**Comment by zioproto** [comment]
@PolynomialDivision is it olsrd core code affected or it is an extension/plugin ? Is it just the [Smart Gateway extension](https://github.com/OLSR/olsrd/blob/v0.9.8/README-Olsr-Extensions#L221) broken ?

**Comment by aparcar** [comment]
@openwrt/routing-write  heads up, firewall4 gets into a fine state (thanks to @stintel and @jow- )and I'm planing to make it the default within the next week. For all scripts that require _legacy_ `iptables` please test your apps with `iptables-nft` and report back!

**Comment by bluewavenet** [comment]
@aparcar 
Where is `iptables-nft`? (It is probably hidden in clear sight, ie I can't find it :-D )
openNDS works fine with it on "Generic Linux" eg Debian, et al, so should be good here as well at least as an interim solution.

**Comment by wfleurant** [comment]
i found something in LuCI. When I Save & Apply a rule under "Traffic Rules" it does not restart the firewall.  
when manually running `/etc/init.d/firewall restart` then all of the rules I enabled/disabled work as expected.  
compiled against your aparcar/openwrt:fw4 (8af05a1) .. tested on rpi4

**Comment by castillofrancodamian** [comment]
> @aparcar Where is `iptables-nft`? (It is probably hidden in clear sight, ie I can't find it :-D ) openNDS works fine with it on "Generic Linux" eg Debian, et al, so should be good here as well at least as an interim solution.

The `iptables-nft` package is already there.

**Comment by aparcar** [comment]
As discussed at yesterdays meeting I merged the changes. The next release will use `firewall4` as default and all packages incompatible (e.g. using `ipset`) should add a negative dependency. Our considerations are that the default (WiFI home router) setup works fine wir `firewall4` and special cases can always replace `firewall4` with `firewall3`, which should work at least until the upcoming 5.15 Kernels.

**Comment by PolynomialDivision** [comment]
Firewall4 fails when adding:
```
config rule                    
        option name 'DSCP olsr'                          
        list proto 'udp'                
        option dest 'freifunk'          
        option dest_port '698'      
        option target 'DSCP'                
        option set_dscp 'EF'      
```

```
/proc/self/fd/0:182:21-27: Error: Byteorder mismatch: expected big endian, got host endian
```

**Comment by jow-** [comment]
Please attach the output of `fw4 print`. Looks like an nftables upstream bug though

**Comment by dave14305** [comment]
> Please attach the output of `fw4 print`. Looks like an nftables upstream bug though

Like this one?
http://git.netfilter.org/nftables/commit/?id=4788869a3346b5b3f1f6a3cdb12fdf79da961ef9

nftables 1.0.2 was released recently.

**Comment by BKPepe** [comment]
> nftables 1.0.2 was released recently.

https://github.com/openwrt/openwrt/pull/9402

**Comment by PolynomialDivision** [comment]
Sorry for closing. This was automatically one by merging the PR.

**Comment by BKPepe** [comment]
Why this was re-opened? It is not clear to me. OP issue was solved. The issue related to nftables or firewall4 should be moved to somewhere else. :)

**Comment by PolynomialDivision** [comment]
Probably @aparcar wants to decide when to close. ;)

**Comment by aparcar** [comment]
If OLSR is the only package affected by firewall4 this can be closed.
