### ISSUE TITLE
SMCRoute: Please update package - version 2.5.3 contained a bug

### ISSUE THREAD

**Issue by NilsRo** [openwrt/routing#744]
Maintainer: @mwarning
Environment: ipq806x, 21.02.0

Description: I have recurring issues with smcroute 2.4.4 and the smcroute developer asked to update to newest version 2.5.3, as the code was refactored. Thanks for the fast update of the package. Right after it developer provided a bugfix for OpenWRT. You can find details here: https://github.com/troglobit/smcroute/issues/169#issuecomment-9392532. It was not included in the OpenWRT pull https://github.com/openwrt/packages/pull/16841 and reduces logging messages.

Many thanks and sorry for the double work.

**Comment by PolynomialDivision** [comment]
Why do you open this here and not in openwrt/packages?

**Comment by mwarning** [comment]
There is already a MR here: https://github.com/openwrt/packages/pull/16847
But the patch is making problems.
