### ISSUE TITLE
[19.07] treewide: missing PKG_MIRROR_HASH

### ISSUE THREAD

**Issue by BKPepe** [openwrt/routing#804]
Maintainers: @openwrt/routing-write
Environment: OpenWrt 19.07

Description:

- Missing PKG_MIRROR_HASH causes that the build is taking longer period than it should. 
This leads that it recreate the tarball once the package is rebuild. 

Affected packages:

- [ ] mrd6
Pull request to the master branch: https://github.com/openwrt/routing/pull/743
- [ ] cjdns
In the master branch fixed by https://github.com/openwrt/routing/pull/526
- [ ] hnetd
Fixed in the master branch by https://github.com/openwrt/routing/pull/628
- [ ] mcproxy
Fixed in the master branch by https://github.com/openwrt/routing/pull/743
- [ ] minimalist-pcproxy
Pull request to the master branch: https://github.com/openwrt/routing/pull/743
- [ ] ohybridproxy
Fixed in the master branch by https://github.com/openwrt/routing/pull/629
- [ ] olsrd
Fixed in the master branch by https://github.com/openwrt/routing/commit/2b6a4e1beb06f8f467f11ba9ae2ab71628450898
- [ ] oonf-dlep-proxy
Fixed in the master branch by https://github.com/openwrt/routing/commit/1d10931616ce029b33695e1e6c6d244788da0943
- [ ] oonf-dlep-radio
Fixed in the master branch by https://github.com/openwrt/routing/pull/688
- [ ] oonf-olsrd2
Fixed in the master branch by https://github.com/openwrt/routing/pull/686
- [ ] pimbd
Fixed in the master branch by https://github.com/openwrt/routing/pull/743

For most packages, it was fixed recently in the master branch or there are pending pull requests. Some of them was backported to OpenWrt 21.02.

**Comment by aparcar** [comment]
Could you please link those PRs/commits to your todo list? That should speed up the back porting.

**Comment by BKPepe** [comment]
I will add it, but it is a question if the version used in newer branches is the same as in OpenWrt 19.07. If not, then PKG_MIRROR_HASH needs to be changed accordingly.

**Comment by BKPepe** [comment]
Added.

**Comment by aparcar** [comment]
Since you have commit access, would you mind back porting those yourself?

**Comment by BKPepe** [comment]
I don't have commit access in this repository.

**Comment by aparcar** [comment]
Sorry I didn't know you have no commit access here. Do you maintain any packages within routing.git? If so I'm happy to add you to the @openwrt/routing-write group, if not I'd prefer that maintainers of package merge PRs. There were some merges in the past where people committed things with best intentions but actually breaking packages which the actual maintainers had to fix later on.

**Comment by BKPepe** [comment]
Unfortunately, I am afraid that I don't maintain any package here, which gives me the answer, but you know I can pick some package and become a maintainer of it, but that's not what I am going to do now.

Yeah, I understand the reasoning, but I want to be helpful since now I need to bother with every single thing @PolynomialDivision as I am not aware of any other active member here. Of course, there are exceptions, but I took the initiative to clean up the repository, and I did not receive almost anything from current maintainers. 

It would help me to close some issues here.

**Comment by PolynomialDivision** [comment]
> but I want to be helpful

You were definitely very helpful! :) Thanks a lot. Some maintainers still did not respond of any of the PRs. I hope I did not overrule them by merging the PRs after they were opened for more than a week. I thought it would be a good idea to get the repository in a clean shape before new stable release happens.

**Comment by BKPepe** [comment]
May I request it once again, @aparcar, please? It shouldn't be necessary to maintain any packages here if I want to improve the state of the repository and merge things, which are sitting here for someone with merge privileges for 5 months to take action.

**Comment by aparcar** [comment]
Im fine with that but ideally you ask maintainers of the repo if they'd approve. I barely check on this repo here sadly

**Comment by BKPepe** [comment]
Hey yo, @openwrt/routing-write, could you say something about that? :)

**Comment by tohojo** [comment]
What's the question, exactly?

**Comment by PolynomialDivision** [comment]
I think @BKPepe wants commit access?

**Comment by mwarning** [comment]
no objections from my side

**Comment by tohojo** [comment]
> I think @BKPepe wants commit access?

Alright, no objections from my side either :)

**Comment by aparcar** [comment]
@BKPepe I added you to the @openwrt/routing-write team, please enjoy.
