### ISSUE TITLE
olsrd: faulty version-srting in binary for 21.02.3 (and others?)

### ISSUE THREAD

**Issue by SvenRoederer** [openwrt/routing#874]
Maintainer: @PolynomialDivision
Environment: (OpenWrt 21.02.3; ipq40xx/mikrotik)

When olsrd startup, it reports the following version string

```
daemon.info olsrd[3016]: olsr.org - pre-0.9.9-git_0000000-hash_d67158ab6e850fd1910c489045f47dda successfully started
```

Obviously the "0000000" part is wrong, but also the hash "d67158ab6e850fd1910c489045f47dda" doesn't relate to something known from the package-makefile.

Ideally the upstream-package src-commit should be present.

**Comment by BKPepe** [comment]
Sorry, this was sitting here for a long time. We do have 2024 year now. No one responded to this issue and OpenWrt 21.02 is these days really old and outdated. Because of that, I am closng this.
